"""Python type stubs for the Rust-backed Spider extension module."""

from typing import Any


class Node:
    """A node in the graph."""

    id: int
    labels: list[int]
    access_count: int
    significance: int
    created_at: int
    last_accessed_at: int


class Edge:
    """A raw relationship record."""

    id: int
    source_id: int
    target_id: int
    kind: str


class Memory:
    """
    Spider — bio-inspired graph database with content-addressed blob store.

    Usage::

        db = Memory("./my_graph")
        doc_id = db.create_node(["DOCUMENT"])
        db.set_node_property(doc_id, "title", "My Paper")
        db.close()
    """

    def __init__(
        self,
        path: str,
        w_sig: float | None = None,
        w_freq: float | None = None,
        gravity: float | None = None,
    ) -> None: ...

    # Node CRUD
    def create_node(self, labels: list[str]) -> int: ...
    def get_node(self, id: int) -> Node | None: ...
    def delete_node(self, id: int) -> None: ...
    def get_all_node_ids(self) -> list[int]: ...
    def node_count(self) -> int: ...

    # Relationship CRUD
    def create_rel(self, source_id: int, target_id: int, rel_type: str) -> int: ...
    def get_rel(self, id: int) -> Edge | None: ...
    def delete_rel(self, id: int) -> None: ...
    def get_neighbors(self, node_id: int) -> list[int]: ...
    def get_relationships(
        self,
        node_id: int,
        direction: str,
        rel_type: str | None = None,
    ) -> list[Edge]: ...
    def get_rel_type_name(self, rel_id: int) -> str | None: ...

    # Property Operations
    def set_node_property(self, node_id: int, key: str, value: bool | int | float | str) -> None: ...
    def get_node_property(self, node_id: int, key: str) -> bool | int | float | str | None: ...
    def delete_node_property(self, node_id: int, key: str) -> None: ...
    def get_all_node_properties(self, node_id: int) -> dict[str, Any]: ...
    def set_rel_property(self, rel_id: int, key: str, value: bool | int | float | str) -> None: ...
    def get_rel_property(self, rel_id: int, key: str) -> bool | int | float | str | None: ...
    def delete_rel_property(self, rel_id: int, key: str) -> None: ...
    def get_all_rel_properties(self, rel_id: int) -> dict[str, Any]: ...

    # Query & Retrieval
    def find_nodes_by_label(self, label: str) -> list[int]: ...
    def find_nodes_by_property(self, key: str, value: bool | int | float | str) -> list[int]: ...

    # Bio Scoring
    def touch_node(self, id: int) -> None: ...
    def set_significance(self, id: int, significance: int) -> None: ...
    def get_bio_score(self, id: int) -> float: ...
    def set_bio_params(self, w_sig: float, w_freq: float, gravity: float) -> None: ...
    def get_bio_params(self) -> tuple[float, float, float]: ...

    # Content Store
    def file(self, data: bytes, name: str, labels: list[str]) -> int: ...
    def read_file(self, node_id: int) -> bytes: ...
    def delete_file(self, node_id: int) -> None: ...
    def file_stats(self) -> tuple[int, int]: ...
    def file_blobs(self) -> int: ...

    # Lifecycle
    def close(self) -> None: ...
    def is_open(self) -> bool: ...
